
classes:
- system.linux.system.single
#- system.openssh.server.team.lab
- system.openssh.server.team.tcpcloud
#- system.openssh.server.team.services
#- system.openssh.server.team.networking
#- system.openssh.server.team.stacklight
- system.rsyslog.client.single
- cluster.mcp-demo.openstack
- cluster.mcp-demo.opencontrail
- cluster.mcp-demo.stacklight
- system.heka.log_collector.single
- system.heka.log_collector.output.telegraf
- system.telegraf.agent
- system.prometheus.collector
- service.grafana.collector
- cluster.mcp-demo.oss
- cluster.mcp-demo.cicd
#- cluster.mcp-demo.infra.proxy
parameters:
  _param:
    # Don't set it "false" before you configure sudo policies and enable power users.
    linux_system_user_sudo: true

    apt_mk_version: stable

    salt_control_trusty_image: http://images.mirantis.com/ubuntu-14-04-x64-mcp${_param:apt_mk_version}.qcow2
    salt_control_xenial_image: http://images.mirantis.com/ubuntu-16-04-x64-mcp${_param:apt_mk_version}.qcow2
    infra_config_hostname: cfg01
    salt_minion_ca_host: ${_param:infra_config_hostname}.${_param:cluster_domain}
    # infra service addresses
    infra_config_address: 10.167.4.15
    infra_config_deploy_address: 172.17.32.253

    cluster_domain: deploy-name.local
    cluster_name: mcp-demo
    cluster_public_host: ${_param:openstack_proxy_address}

    control_network_netmask: 255.255.255.0
    tenant_network_netmask: 255.255.255.0

    dns_server01: 8.8.8.8
    dns_server02: 8.8.4.4
    tenant_network_gateway: 10.167.5.1
    control_vlan: 2428
    tenant_vlan: 2429

    deploy_network_netmask: 255.255.255.192
    deploy_network_gateway: 172.17.32.193

    # MaaS parameters
    infra_maas_node01_deploy_address: ${_param:infra_config_deploy_address}
    infra_maas_node01_hostname: ${_param:infra_config_hostname}
    maas_admin_username: mirantis
    maas_admin_password: r00tme
    maas_db_password: fRqC7NJrBR0x
    infra_kvm_address: 10.167.4.240
    infra_kvm_node01_address: 10.167.4.241
    infra_kvm_node02_address: 10.167.4.242
    infra_kvm_node03_address: 10.167.4.243
    infra_kvm_node01_deploy_address: 172.17.32.195
    infra_kvm_node02_deploy_address: 172.17.32.196
    infra_kvm_node03_deploy_address: 172.17.32.197
    infra_kvm_node01_hostname: kvm01
    infra_kvm_node02_hostname: kvm02
    infra_kvm_node03_hostname: kvm03

    glusterfs_node01_address: ${_param:infra_kvm_node01_address}
    glusterfs_node02_address: ${_param:infra_kvm_node02_address}
    glusterfs_node03_address: ${_param:infra_kvm_node03_address}
    linux_dhcp_interface:
      enabled: true
      type: eth
      proto: dhcp
    linux_single_interface:
      enabled: true
      type: eth
      proto: static
      address: ${_param:single_address}
      netmask: ${_param:control_network_netmask}
      name_servers:
        - ${_param:dns_server01}
        - ${_param:dns_server02}

  salt:
    minion:
      trusted_ca_minions:
        - ${_param:salt_minion_ca_host}

  linux:
    network:
      dhclient:
        enabled: true
        request:
          - subnet-mask
          - broadcast-address
          - time-offset
          - routers
          - domain-name
          - domain-name-servers
          - domain-search
          - host-name
          - dhcp6.name-servers
          - dhcp6.domain-search
          - dhcp6.fqdn
          - dhcp6.sntp-servers
          - netbios-name-servers
          - netbios-scope
          - interface-mtu
          - rfc3442-classless-static-routes
      host:
        hostname:
          address: ${_param:single_address}
          names:
          - ${linux:network:hostname}
          - ${linux:network:fqdn}
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - ${_param:infra_config_hostname}
          - ${_param:infra_config_hostname}.${_param:cluster_domain}
        cfg:
          address: ${_param:infra_config_address}
          names:
          - cfg
          - cfg.${_param:cluster_domain}
        kvm01:
          address: ${_param:infra_kvm_node01_address}
          names:
          - ${_param:infra_kvm_node01_hostname}
          - ${_param:infra_kvm_node01_hostname}.${_param:cluster_domain}
        kvm02:
          address: ${_param:infra_kvm_node02_address}
          names:
          - ${_param:infra_kvm_node02_hostname}
          - ${_param:infra_kvm_node02_hostname}.${_param:cluster_domain}
        kvm03:
          address: ${_param:infra_kvm_node03_address}
          names:
          - ${_param:infra_kvm_node03_hostname}
          - ${_param:infra_kvm_node03_hostname}.${_param:cluster_domain}
    system:
      name: ${_param:infra_config_hostname}
      domain: ${_param:cluster_domain}
      service:
        apt-daily.timer:
          status: dead
